#分布式的各个项目都应该有自己的端口号和应用名称
server:
  port: 8001

spring:
  application:
    name: cloud-payment-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/mycloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.bjming.springcloud.entities    # 所有Entity别名类所在包

# eureka的配置
eureka:
  client:
    # 表示是否将自己注册进EurekaServer, 默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息, 默认为true, 单节点无所谓, 集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
      # 将服务注册进eureka集群中
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/

  instance:
    #修改主机名称, 不要配置错了, hostName是主机的ip
    instance-id: payment8001
    #访问路径显示ip地址
    prefer-ip-address: true
    # Eureka客户端向服务端发送心跳的时间间隔, 单位为秒(默认30秒)
    lease-renewal-interval-in-seconds: 1
    # Eureka服务端在收到最后依次心跳后等待时间上限, 单位为秒(默认为90秒), 超时将剔除服务;
    lease-expiration-duration-in-seconds: 2
